version: "3"
networks:
  restos-a-pagar-net:
    driver: bridge
services:
  database:
    container_name: database
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: S3cr3t00
    image: microsoft/mssql-server-linux
    networks:
      - restos-a-pagar-net
    ports:
      - 1433:1433
    restart: always
    volumes:
      - "./database:/var/opt/database"
  auth_api:
    container_name: auth-api
    environment:
      APP_PATH: ""
      AUTH_DRIVER: "inMemory"
      AUTH_SECRET: secret
      AUTH_EXPIRATION: 21600
      AUTH_ISSUER: SUDEP
    image: praser/api-autenticacao:1.2.0
    networks:
      - restos-a-pagar-net
    ports:
      - 3001:3000
  smtp:
    container_name: smtp
    image: marcopas/docker-mailslurper
    networks:
      - restos-a-pagar-net
    ports:
      - 8080:8080
      - 2500:2500
      - 8085:8085
  backend:
    image: praser/api-restos-a-pagar
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - database
    networks:
      - restos-a-pagar-net
    ports:
      - 3000:80
    volumes:
      - "./backend:/var/www/html"
  web:
    image: praser/web-restos-a-pagar
    build:
      context: ./web
    container_name: web
    depends_on:
      - backend
      - auth_api
    networks:
      - restos-a-pagar-net
    ports:
      - 3002:3000
    volumes:
      - "./web:/app"
    stdin_open: true
