import { formatDate, parseISO } from '~/utils/dates';
import { formatPercent, formatCurrency } from '~/utils/numbers';

export const csvHeaders = [
  { key: 'anoExecucao' },
  { key: 'anoOrcamentario' },
  { key: 'operacao' },
  { key: 'dv' },
  { key: 'anoOrcamentarioProposta' },
  { key: 'convenio' },
  { key: 'dataCumprimentoCriteriosDesbloqueio' },
  { key: 'aptaDesbloqueio' },
  { key: 'gigovNome' },
  { key: 'proponente' },
  { key: 'uf' },
  { key: 'siglaGestor' },
  { key: 'nomeGestor' },
  { key: 'enquadramentoLegislacao' },
  { key: 'situacaoContratoComplemento' },
  { key: 'percentualFisicoAferido' },
  { key: 'percentualFinanceiroDesbloqueado' },
  { key: 'dataVigencia' },
  { key: 'dataSPA' },
  { key: 'dataVRPL' },
  { key: 'dataAIO' },
  { key: 'valorRepasse' },
  { key: 'objeto' },
  { key: 'valorDesembolsado' },
];

export const operacoesColumns = [
  { name: 'Operação', selector: 'operacao', sortable: true },
  { name: 'Convênio', selector: 'convenio', sortable: true },
  { name: 'Ano orçamento', selector: 'anoOrcamentario', sortable: true },
  {
    name: 'Retirada da suspensiva',
    selector: 'dataRetiradaSuspensiva',
    sortable: true,
    grow: 2,
    format: row => formatDate(parseISO(row.dataRetiradaSuspensiva)),
  },
  {
    name: 'Fim vigência',
    selector: 'dataVigencia',
    sortable: true,
    grow: 2,
    format: row => formatDate(row.dataVigencia),
  },
  { name: 'GIGOV', selector: 'gigovNome', sortable: true },
  {
    name: 'Valor repasse',
    selector: 'valorRepasse',
    sortable: true,
    format: row => {
      return formatCurrency(row.valorDesembolsado);
    },
  },
  {
    name: 'Valor desembolsado',
    selector: 'valorDesembolsado',
    sortable: true,
    format: row => formatCurrency(row.valorDesembolsado),
  },
  {
    name: 'Proponente',
    selector: 'proponente',
    sortable: true,
    grow: 3,
    format: row => `${row.proponente}/${row.uf}`,
  },
  {
    name: 'Gestor',
    selector: 'nomeGestor',
    sortable: true,
    grow: 3,
    format: row => `${row.siglaGestor} - ${row.nomeGestor}`,
  },
  {
    name: 'Legislação',
    selector: 'enquadramentoLegislacao',
    sortable: true,
    grow: 2,
  },
  {
    name: 'Situação complemento',
    selector: 'situacaoContratoComplemento',
    sortable: true,
    grow: 3,
  },
  {
    name: '% físico aferido',
    selector: 'percentualFisicoAferido',
    sortable: true,
    format: row => formatPercent(row.percentualFisicoAferido),
  },
  {
    name: '% financeiro desbloqueado',
    selector: 'percentualFinanceiroDesbloqueado',
    sortable: true,
    format: row => formatPercent(row.percentualFinanceiroDesbloqueado),
  },
  {
    name: 'SPA',
    selector: 'dataSPA',
    sortable: true,
    grow: 2,
    format: row => formatDate(row.dataSPA),
  },
  {
    name: 'VRPL',
    selector: 'dataVRPL',
    sortable: true,
    grow: 2,
    format: row => formatDate(row.dataVRPL),
  },
  {
    name: 'AIO',
    selector: 'dataAIO',
    sortable: true,
    grow: 2,
    format: row => formatDate(row.dataAIO),
  },
  { name: 'Objeto', selector: 'objeto', sortable: true, grow: 10 },
];
