import styled from 'styled-components';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

export const Collapsable = styled.div`
  animation-duration: 0.2s;
  animation-name: growIn;
  animation-timing-function: ease;
  background-clip: padding-box;
  background-color: rgb(255, 255, 255);
  border-radius: 0.35rem;
  border-style: solid;
  border-width: 1px;
  border-image-outset: 0;
  border-image-repeat: stretch;
  border-image-slice: 100%;
  border-image-source: none;
  border-image-width: 1;
  border-color: rgb(227, 230, 240);
  box-shadow: rgba(58, 59, 69, 0.15) 0 0.15rem 1.75rem 0;
  box-sizing: border-box;
  color: rgb(133, 135, 150);
  display: ${props => (props.expanded ? 'block' : 'none')};
  float: none;
  font-size: 0.85rem;
  font-weight: 400;
  line-height: 1.5;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  margin: 0.125rem 0 0;
  min-width: 10rem;
  padding: 0.5rem 0;
  position: absolute;
  right: 0;
  text-align: left;
  text-size-adjust: 100%;
  top: 100%;
  z-index: 1000;
`;

export const CollapsableLink = styled.a`
  background-color: rgba(0, 0, 0, 0);
  border-color: rgb(58, 59, 69);
  border-image-outset: 0;
  border-image-repeat: stretch;
  border-image-slice: 100%;
  border-image-source: none;
  border-image-width: 1;
  box-sizing: border-box;
  clear: both;
  color: rgb(58, 59, 69);
  cursor: pointer;
  display: block;
  font-size: 0.85rem;
  font-weight: 400;
  line-height: 1.5;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  padding: 0.25rem 1.5rem;
  text-align: left;
  text-decoration-color: rgb(58, 59, 69);
  text-decoration-line: none;
  text-decoration-style: solid;
  text-size-adjust: 100%;
  white-space: nowrap;
  width: 100%;
`;

export const Container = styled.li`
  box-sizing: border-box;
  color: rgb(133, 135, 150);
  display: list-item;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  position: relative;
  text-align: left;
  text-size-adjust: 100%;
  width: 107.578px;
`;

export const Button = styled.button`
  align-items: center;
  background-color: rgba(0, 0, 0, 0);
  box-sizing: border-box;
  color: rgb(209, 211, 226);
  cursor: pointer;
  display: flex;
  font-size: 1rem;
  font-weight: 400;
  height: 4.375rem;
  line-height: 1.5;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  padding: 0 0.75rem;
  position: relative;
  text-align: left;
  text-decoration-color: rgb(209, 211, 226);
  text-decoration-line: none;
  text-decoration-style: solid;
  text-size-adjust: 100%;
  white-space: nowrap;
  border: none;
  outline: none;
`;

export const Name = styled.span`
  box-sizing: border-box;
  color: rgb(133, 135, 150);
  cursor: pointer;
  display: block;
  font-size: 80%;
  font-weight: 400;
  line-height: 1.5px;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  margin-right: 0.5rem;
  text-align: left;
  text-size-adjust: 100%;
  white-space: nowrap;
`;

export const Avatar = styled.img`
  border-bottom-left-radius: 50%;
  border-bottom-right-radius: 50%;
  border-bottom-style: none;
  border-left-style: none;
  border-right-style: none;
  border-top-left-radius: 50%;
  border-top-right-radius: 50%;
  border-top-style: none;
  box-sizing: border-box;
  color: rgb(209, 211, 226);
  cursor: pointer;
  display: block;
  font-size: 1rem;
  font-weight: 400;
  height: 2rem;
  line-height: 1.5;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  text-align: left;
  text-size-adjust: 100%;
  white-space: nowrap;
  width: 2rem;
`;

export const Icon = styled(FontAwesomeIcon)`
  box-sizing: border-box;
  color: rgb(209, 211, 226);
  cursor: pointer;
  display: inline-block;
  font-family: 'Font Awesome 5 Free';
  font-size: 0.875rem;
  font-style: normal;
  font-weight: 900;
  line-height: 1;
  list-style-image: none;
  list-style-position: outside;
  list-style-type: none;
  margin-right: 0.5rem;
  text-align: center;
  text-rendering: auto;
  text-size-adjust: 100%;
  white-space: nowrap;
  width: 1.25rem;
`;
